configured_endpoints: 11
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/reducto%2Freductoai-d358ebcc07d509d6eb417a5f431b1ee7cba14f4fa041bed173887d4818b3aaf8.yml
openapi_spec_hash: c0acff4c5fc94d23eae0b3c5a8ebece6
config_hash: bfd902be3e7f324d12d37483f51521ab
