configured_endpoints: 11
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/reducto%2Freductoai-de06f9ac859d5d85157263eb21fdeb7eb80aedf7fd95fbcee896adda760e65f4.yml
openapi_spec_hash: 5680634c6caeed1cf4ddf131bb4d98bc
config_hash: 79ae6ecc01ff99160ea8abc4895bff4f
