configured_endpoints: 11
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/reducto%2Freductoai-8686df2d99d52f27cec7bb7b44743f12cbf0c90a5c8fc8fda4aa42e8ca455e3b.yml
openapi_spec_hash: 9ab7b8ddcbd4ded368bc063d623a8587
config_hash: 79ae6ecc01ff99160ea8abc4895bff4f
