configured_endpoints: 11
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/reducto%2Freductoai-1d79afe8ddb995fe4415501c284a3dee24379a61ccdeeb54ec2e2c25016b7299.yml
openapi_spec_hash: 0ef5d4ff39e1682ed0ccad7fc9e2d5fb
config_hash: 79ae6ecc01ff99160ea8abc4895bff4f
