#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

export DEFER_PYDANTIC_BUILD=false

echo "==> Running tests"
uv run pytest "$@"

echo "==> Running Pydantic v1 tests"
uv run --isolated --with "pydantic<2" pytest --showlocals --ignore=tests/functional "$@"
